branches:
  except:
    - /travis/
    - /github-actions/
    - /doozer/
skip_tags: true

#cache:
#  - C:\strawberry

environment:
  matrix:
## ppm downloads do not work anymore, since beginning of June 2024
#    - perl: activeperl
#      make: dmake
    - perl: cygwinperl
      make: make
    - perl: strawberryperl
      make: gmake

install:
  - if %perl%==strawberryperl ( if not exist "C:\strawberry" cinst strawberryperl )
  - if %perl%==strawberryperl   set PATH=C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - if not %perl%==cygwinperl perl -v
  - if     %perl%==cygwinperl c:\cygwin\bin\sh -c "/usr/bin/perl -v"
  - cd %APPVEYOR_BUILD_FOLDER%
  - if %perl%==activeperl       ppm install dmake

build_script:
  - if     %perl%==cygwinperl   c:\cygwin\bin\sh -c "PATH=/usr/bin:/bin; perl Makefile.PL && $make test"
  - if not %perl%==cygwinperl ( perl Makefile.PL && %make% test )
